config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :subscriptions do
    collection do
      get 'subscription_type_list', to: 'subscriptions#subscription_type_list'
      get 'success', to: 'subscriptions#success'
      get 'cancel', to: 'subscriptions#cancel'
    end
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
# frozen_string_literal: true

# subscription class
class Subscription < ApplicationRecord
  belongs_to :subscription_category
  belongs_to :user
  has_one :subscription_payment

  enum status: { inactive: 10, active: 20, expired: 30 }
end

app/models/subscription_category.rb
# frozen_string_literal: true

# subscription_category class
class SubscriptionCategory < ApplicationRecord
  has_many :subscriptions
end

app/models/subscription_payment.rb
# frozen_string_literal: true

# subscription payment class
class SubscriptionPayment < ApplicationRecord
  belongs_to :subscription

  enum status: { pending: 10, hold: 20, paid: 30 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :subscriptions

  def active_subscription
    subscriptions.where(status: 'active').last
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

# subscription controller
class SubscriptionsController < ApplicationController
  def show
    @subscription = Subscription.find params[:id]
  end

  def new
    @subscription = Subscription.new
    @subscription_type = SubscriptionCategory.find params[:subscription_type]
  end

  def create
    subscription_category = SubscriptionCategory.find params[:subscription][:subscription_category]

    subscription = Subscription.new(subscription_category: subscription_category, user: current_user, start_date: Date.today, end_date: Date.today + subscription_category.duration.months, status: 'inactive')
    payment = subscription.build_subscription_payment(amount: subscription_category.price, mode: 'online', status: 'pending')
    subscription.save

    @session = Stripe::Checkout::Session.create(
      customer_email: current_user.email,
      payment_method_types: ['card'],
      line_items: [{
        name: "#{subscription_category.title} Subscription",
        description: "Please pay for your #{subscription_category.title} (#{subscription_category.code}) Subscription.",
        amount: subscription_category.price * 100,
        currency: 'inr',
        quantity: 1
      }],
      success_url: success_subscriptions_url + "?session_id={CHECKOUT_SESSION_ID}&sub_id=#{subscription.id}",
      cancel_url: cancel_subscriptions_url
    )
    respond_to do |format|
      format.js
    end
  end

  def success
    subscription = Subscription.find params[:sub_id]
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
    payment_intent = Stripe::PaymentIntent.retrieve(session.payment_intent)
    payment = subscription.subscription_payment
    payment.update_attributes(status: 'paid', stripe_session_id: session.id, stripe_payment_id: payment_intent.id)
    subscription.update_attributes(status: 'active')
  end

  def cancel; end

  def subscription_type_list
    @subscription_types = SubscriptionCategory.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
</br>
<div class='row text-center'>
  <div class='col-md-6'>
    <%= link_to 'Home', root_path %>
  </div>
  <div class='col-md-6'>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
    <% else %>
      <%= link_to('Login', new_user_session_path) %>  
    <% end %>
  </div>
</div>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subscription Channel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render '/layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/subscriptions/cancel.html.erb
<div class= 'row text-center'>
  <div class='col-md-12'>
    <div class='row'>
      <div class='col-md-12'>
        <img src="https://i.pinimg.com/originals/95/8d/fc/958dfc02a52c20b9f6b77ac15d58e93a.gif" style="
    height: 300px;
" />
      </div>
    </div>
    <div class='row'  style="padding-bottom: 50px;">
      <div class='col-md-12'>
        <h2>Something went wrong please contact at care@subscriptio.com</h2>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function (result) {
  console.log(result.error.message);
});

app/views/subscriptions/new.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='row text-center'>
      <div class='col-md-12'>
        Payment  
      </div>
      </br></br></br>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <% if @subscription.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@subscription.errors.count, "error") %> prohibited
              this subscription from being saved:
            </h2>
            <ul>
              <% @subscription.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-2'></div>
      <div class='col-md-8'>
        <%= form_with model: @subscription, remote: true do |form| %>
          <%= form.hidden_field :subscription_category, value: @subscription_type.id %>
          <table class="table text-center">
            <tr>
              <th>Subscription Type</th>
              <th>Code</th>
              <th>Duration( in months )</th>
              <th>Price</th>
            </tr>
              <tr>
                
                <td>
                  <%= @subscription_type.title %>
                </td>
                <td>
                  <%= @subscription_type.code %>
                </td>
                <td>
                  <%= @subscription_type.duration %>
                </td>
                <td>
                  <%= @subscription_type.price %>
                </td>
              </tr>
            <tr>
              <td colspan='4' class='text-center'><%= form.submit "Pay Now" %></td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class='col-md-2'></div>
    </div>
  </div>
</div>

app/views/subscriptions/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='row text-center'>
      <div class='col-md-12'>
        Your subscription  
      </div>
      </br></br></br>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <% if @subscription.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@subscription.errors.count, "error") %> prohibited
              this subscription from being saved:
            </h2>
            <ul>
              <% @subscription.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-2'></div>
      <div class='col-md-8'>
        <%= form_with model: @subscription, remote: true do |form| %>
          <table class="table text-center">
            <tr>
              <th>Subscription Type</th>
              <th>Code</th>
              <th>Duration( in months )</th>
              <th>Price</th>
            </tr>
              <tr>
                <td>
                  <%= @subscription.subscription_category.title %>
                </td>
                <td>
                  <%= @subscription.subscription_category.code %>
                </td>
                <td>
                  <%= @subscription.subscription_category.duration %>
                </td>
                <td>
                  <%= @subscription.subscription_category.price %>
                </td>
              </tr>
          </table>
        <% end %>
      </div>
      <div class='col-md-2'></div>
    </div>
  </div>
</div>

app/views/subscriptions/subscription_type_list.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='row text-center'>
      <div class='col-md-12'>
        Select Subscripion Package 
      </div>
      </br></br></br>
    </div>
    <div class='row'>
      <div class='col-md-2'></div>
      <div class='col-md-8'>
        <%= form_with(url: "/subscriptions/new", method: "get", local: true ) do |form| %>
          <table class="table text-center">
            <tr>
              <th></th>
              <th>Subscription Type</th>
              <th>Code</th>
              <th>Duration( in months )</th>
              <th>Price</th>
              <th>Select</th>
            </tr>
            <% @subscription_types.each_with_index do |subscription_type, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td>
                  <%= subscription_type.title %>
                </td>
                <td>
                  <%= subscription_type.code %>
                </td>
                <td>
                  <%= subscription_type.duration %>
                </td>
                <td>
                  <%= subscription_type.price %>
                </td>
                <td>
                  <%= form.radio_button :subscription_type, "#{subscription_type.id}", id: 'radioButton', onClick: "ShowHideDiv()"%>
                </td>
              </tr>
            <% end %>
            <tr>
              <td colspan='6' class='text-center'>
              <%= form.submit "Subscribe", id: 'submitButton', style: "display: none"%></td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class='col-md-2'></div>
    </div>
  </div>
</div>

<script>
  function ShowHideDiv() {
        var chkYes = document.getElementById("radioButton");
        var submitButton = document.getElementById("submitButton");
        submitButton.style.display = "block";
    }
</script>

app/views/subscriptions/success.html.erb
<div class= 'row text-center'>
  <div class='col-md-12'>
    <div class='row'>
      <div class='col-md-12'>
        <img src="https://i.pinimg.com/originals/95/8d/fc/958dfc02a52c20b9f6b77ac15d58e93a.gif" style="
    height: 300px;
" />
      </div>
    </div>
    <div class='row'  style="padding-bottom: 50px;">
      <div class='col-md-12'>
        <h2>Thank you so much for your subscription.</h2>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class= 'row text-center'>
  <div class='col-md-12'>
    <div class='row'>
      <div class='col-md-12'>
        <img src="https://i.pinimg.com/originals/95/8d/fc/958dfc02a52c20b9f6b77ac15d58e93a.gif" style="
    height: 300px;
" />
      </div>
    </div>
    <div class='row'  style="padding-bottom: 50px;">
      <div class='col-md-12'>
        <h2>Welcome To Ruby Subscription</h2>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-4'>
        <a href="#">Link 1</a>
      </div>
      <div class='col-md-4'>
        <a href="#">Link 2</a>
      </div>
      <div class='col-md-4'>
      <% if current_user.active_subscription.present? %>
        <%= link_to 'Manage Preminum', subscription_path(current_user.active_subscription.id) %>
      <% else %>
        <%= link_to 'Go Preminum', subscription_type_list_subscriptions_path %>
      <% end%>
      </div>
    </div>
  </div>
</div>